site_name: My Software & Data Science Portfolio
site_url: https://aldojasb.github.io/general_projects/

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    scheme: default
  icon:
    logo: material/book

nav:
  - Home: index.md
  - Software Architecture:
      - Overview: guides/software_architecture/overview.md
      - SOLID Principles: guides/software_architecture/SOLID_principles.md
  - Unit Testing:
      - Overview: guides/unit_testing/overview.md
  - Deep Learning:
      - Overview: guides/deep_learning/overview.md
  - Projects:
      - Overview: guides/projects/overview.md

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true

plugins:
  - search
  - sitemap:
      changefreq: weekly
      priority: 0.5
