site_name: Aldo Saltao's Portfolio
site_url: https://aldojasb.github.io/general_projects/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    scheme: default
  icon:
    logo: material/book

nav:
  - Home: index.md
  - Software Architecture:
      - Overview: guides/software_architecture/overview.md
      - SOLID Principles: guides/software_architecture/SOLID_principles.md
  - Workflows:
      - Overview: guides/workflows/overview.md
      - The MoSCoW Method: guides/workflows/the_moscow_method.md
      - The Skateboard Mindset: guides/workflows/skateboard_mindset.md
  - Data Science & AI:
      - Overview: guides/data_science_and_ai/overview.md
      - Data Science Products as Python Packages: guides/data_science_and_ai/ds_products_as_python_packages.md
  - Development & DevOps:
      - Overview: guides/development_and_devops/overview.md
      - Test-Driven Development (TDD): guides/development_and_devops/tdd_tutorial.md
      - Versioning package on GitHub: guides/development_and_devops/versioning_tutorial.md
      - Documentation with mkdocs: guides/development_and_devops/mkdocs_tutorial.md
  - Projects:
      - Overview: guides/projects/overview.md

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true

plugins:
  - search
