site_name: My Software & Data Science Portfolio
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    scheme: default

nav:
  - Home: guides/index.md
  - Software Architecture:
      - Overview: guides/software_architecture/overview.md
      - SOLID Principles: guides/software_architecture/SOLID_principles.md
  - Unit Testing:
      - Overview: guides/unit_testing/overview.md
  - Deep Learning:
      - Overview: guides/deep_learning/overview.md
  - Projects:
      - Overview: guides/projects/overview.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true

plugins:
  - search

