site_name: Aldo Saltao's Portfolio
site_url: https://aldojasb.github.io/general_projects/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    scheme: default
  icon:
    logo: material/book

nav:
  - Home: index.md
  - Software Architecture:
      - Overview: guides/software_architecture/overview.md
      - SOLID Principles: guides/software_architecture/SOLID_principles.md
  - AI Product Development:
      - Overview: guides/ai_product_development/overview.md
      - Framework That Embraces Uncertainty: guides/ai_product_development/framework_that_embraces_uncertainty.md
      - The MoSCoW Method: guides/ai_product_development/the_moscow_method.md
      - The Skateboard Mindset: guides/ai_product_development/skateboard_mindset.md
  - Data Science & AI:
      - Overview: guides/data_science_and_ai/overview.md
      - The Neutal Network Structure: guides/data_science_and_ai/neutal_networking_example_1.md
      - Data Science Products as Python Packages: guides/data_science_and_ai/ds_products_as_python_packages.md
      - Clustering Algorithms: guides/data_science_and_ai/clustering_algorithms.md
      - Clustering Algorithms Visualization: guides/data_science_and_ai/k-means_visualization.md
  - Development & DevOps:
      - Overview: guides/development_and_devops/overview.md
      - Introduction to Dev-Container: guides/development_and_devops/introduction_to_dev_container.md
      - Loggin Manager Package: guides/development_and_devops/logging_manager_package.md
      - Test-Driven Development (TDD): guides/development_and_devops/tdd_tutorial.md
      - Versioning package on GitHub: guides/development_and_devops/versioning_tutorial.md
      - Documentation with mkdocs: guides/development_and_devops/mkdocs_tutorial.md
  - Projects:
      - Overview: guides/projects/overview.md

extra_css:
  - assets/stylesheets/extra.css

# extra_javascript:
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#   - assets/javascripts/extra.js
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - assets/javascripts/extra.js

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

plugins:
  - search
